In [134]:
import os
import pandas as pd
import numpy as np

In [135]:
# Obtendo o diret√≥rio atual do notebook
notebook_dir = %pwd

# Construindo o caminho completo para data.csv
file_path = os.path.join(notebook_dir, '..', 'data', 'processed', 'data.csv')

In [136]:
# Lendo o arquivo CSV usando pandas
data_raw = pd.read_csv(file_path)

data = data_raw.copy()

#Exibe as 5 primeiras linhas do dataframe
data.head(12)

,game,game_time,blue_team,blue_team_dragons,blue_team_gold,blue_team_inhibitors,blue_team_barons,blue_team_towers,blue_team_kills,blue_team_top,...,red_team_bottom_deaths,red_team_bottom_assists,red_team_bottom_cs,red_team_bottom_gold,red_team_support,red_team_support_kills,red_team_support_deaths,red_team_support_assists,red_team_support_cs,red_team_support_gold
0,1,early,FX,['hextech'],20.5 K,0,0,0,3,Tay,...,0,0,118,4.3 K,Damage,0,0,0,22,2.7 K
1,10,early,LLL,[],18.7 K,0,0,0,4,Robo,...,2,3,57,2.9 K,frostyy,0,1,2,16,2.3 K
2,11,early,RED,[],2.5 K,0,0,0,0,fNb,...,0,0,0,500,Ceos,0,0,0,0,500
3,12,early,RED,[],2.5 K,0,0,0,0,fNb,...,0,0,0,500,Ceos,0,0,0,0,500
4,13,early,VKS,['cloud'],18.8 K,0,0,0,4,Guigo,...,0,2,101,4.6 K,Nia,0,1,3,16,2.4 K
5,14,early,ITZ,"['mountain', 'ocean']",21.3 K,0,0,0,1,Zzk,...,0,0,133,5.3 K,Damage,0,0,1,20,2.8 K
6,15,early,ITZ,[],30.4 K,0,0,1,5,Zzk,...,0,1,181,6.4 K,Damage,0,0,1,28,3.8 K
7,16,early,ITZ,['ocean'],18.0 K,0,0,0,6,Zzk,...,0,1,79,3.2 K,Damage,0,1,1,15,2.2 K
8,17,early,PNG,[],17.3 K,0,0,0,3,Wizer,...,0,1,90,3.4 K,Ceos,0,2,1,13,2.1 K
9,18,early,PNG,[],19.9 K,0,0,0,0,Wizer,...,0,1,124,4.7 K,Ceos,1,0,0,26,3.2 K
10,19,early,LLL,[],17.2 K,0,0,0,4,Robo,...,0,0,90,3.8 K,ProDelta,0,0,0,15,2.3 K
11,2,early,VKS,[],26.3 K,0,0,1,3,Guigo,...,0,3,156,6.8 K,JoJo,2,1,3,23,4.1 K

In [137]:
winners = ['VKS', 'FX', 'VKS', 'FX', 'VKS',
           'PNG', 'PNG', 'PNG',
           'RED', 'LLL', 'LLL', 'LLL',
           'VKS', 'ITZ', 'ITZ', 'ITZ', 
           'LLL', 'LLL', 'LLL',
           'RED', 'ITZ', 'RED', 'RED',
           'PNG', 'RED', 'RED', 'PNG', 'PNG',
           'LLL', 'LLL', 'PNG', 'LLL',
           'VKS', 'FX', 'VKS', 'FX', 'VKS',
           'PNG', 'PNG', 'PNG',
           'RED', 'LLL', 'LLL', 'LLL',
           'VKS', 'ITZ', 'ITZ', 'ITZ', 
           'LLL', 'LLL', 'LLL',
           'RED', 'ITZ', 'RED', 'RED',
           'PNG', 'RED', 'RED', 'PNG', 'PNG',
           'LLL', 'LLL', 'PNG', 'LLL',
           'VKS', 'FX', 'VKS', 'FX', 'VKS',
           'PNG', 'PNG', 'PNG',
           'RED', 'LLL', 'LLL', 'LLL',
           'VKS', 'ITZ', 'ITZ', 'ITZ', 
           'LLL', 'LLL', 'LLL',
           'RED', 'ITZ', 'RED', 'RED',
           'PNG', 'RED', 'RED', 'PNG', 'PNG',
           'LLL', 'LLL', 'PNG', 'LLL']

In [138]:
# Adiciona coluna team_winner
data['team_winner'] = winners

#Exibe as 5 primeiras linhas do dataframe
data.head(12)

,game,game_time,blue_team,blue_team_dragons,blue_team_gold,blue_team_inhibitors,blue_team_barons,blue_team_towers,blue_team_kills,blue_team_top,...,red_team_bottom_assists,red_team_bottom_cs,red_team_bottom_gold,red_team_support,red_team_support_kills,red_team_support_deaths,red_team_support_assists,red_team_support_cs,red_team_support_gold,team_winner
0,1,early,FX,['hextech'],20.5 K,0,0,0,3,Tay,...,0,118,4.3 K,Damage,0,0,0,22,2.7 K,VKS
1,10,early,LLL,[],18.7 K,0,0,0,4,Robo,...,3,57,2.9 K,frostyy,0,1,2,16,2.3 K,FX
2,11,early,RED,[],2.5 K,0,0,0,0,fNb,...,0,0,500,Ceos,0,0,0,0,500,VKS
3,12,early,RED,[],2.5 K,0,0,0,0,fNb,...,0,0,500,Ceos,0,0,0,0,500,FX
4,13,early,VKS,['cloud'],18.8 K,0,0,0,4,Guigo,...,2,101,4.6 K,Nia,0,1,3,16,2.4 K,VKS
5,14,early,ITZ,"['mountain', 'ocean']",21.3 K,0,0,0,1,Zzk,...,0,133,5.3 K,Damage,0,0,1,20,2.8 K,PNG
6,15,early,ITZ,[],30.4 K,0,0,1,5,Zzk,...,1,181,6.4 K,Damage,0,0,1,28,3.8 K,PNG
7,16,early,ITZ,['ocean'],18.0 K,0,0,0,6,Zzk,...,1,79,3.2 K,Damage,0,1,1,15,2.2 K,PNG
8,17,early,PNG,[],17.3 K,0,0,0,3,Wizer,...,1,90,3.4 K,Ceos,0,2,1,13,2.1 K,RED
9,18,early,PNG,[],19.9 K,0,0,0,0,Wizer,...,1,124,4.7 K,Ceos,1,0,0,26,3.2 K,LLL
10,19,early,LLL,[],17.2 K,0,0,0,4,Robo,...,0,90,3.8 K,ProDelta,0,0,0,15,2.3 K,LLL
11,2,early,VKS,[],26.3 K,0,0,1,3,Guigo,...,3,156,6.8 K,JoJo,2,1,3,23,4.1 K,LLL

In [139]:
# Transform column blue_team_dragons and red_team_dragons in numeric columns counting the number of each dragon
data['blue_hextec_dragon'] = data['blue_team_dragons'].str.count('hextech')
data['blue_mountain_dragon'] = data['blue_team_dragons'].str.count('mountain')
data['blue_cloud_dragon'] = data['blue_team_dragons'].str.count('cloud')
data['blue_ocean_dragon'] = data['blue_team_dragons'].str.count('ocean')
data['blue_infernal_dragon'] = data['blue_team_dragons'].str.count('infernal')
data['blue_chemtech_dragon'] = data['red_team_dragons'].str.count('chemtech')
#drop column blue_team_dragons
data.drop('blue_team_dragons', axis=1, inplace=True)

data['red_hextec_dragon'] = data['red_team_dragons'].str.count('hextech')
data['red_mountain_dragon'] = data['red_team_dragons'].str.count('mountain')
data['red_cloud_dragon'] = data['red_team_dragons'].str.count('cloud')
data['red_ocean_dragon'] = data['red_team_dragons'].str.count('ocean')
data['red_infernal_dragon'] = data['red_team_dragons'].str.count('infernal')
data['red_chemtech_dragon'] = data['red_team_dragons'].str.count('chemtech')
#drop column red_team_dragons
data.drop('red_team_dragons', axis=1, inplace=True)

data.head(12)

,game,game_time,blue_team,blue_team_gold,blue_team_inhibitors,blue_team_barons,blue_team_towers,blue_team_kills,blue_team_top,blue_team_top_kills,...,blue_cloud_dragon,blue_ocean_dragon,blue_infernal_dragon,blue_chemtech_dragon,red_hextec_dragon,red_mountain_dragon,red_cloud_dragon,red_ocean_dragon,red_infernal_dragon,red_chemtech_dragon
0,1,early,FX,20.5 K,0,0,0,3,Tay,3,...,0,0,0,0,0,0,0,0,0,0
1,10,early,LLL,18.7 K,0,0,0,4,Robo,0,...,0,0,0,0,1,0,0,0,0,0
2,11,early,RED,2.5 K,0,0,0,0,fNb,0,...,0,0,0,0,0,0,0,0,0,0
3,12,early,RED,2.5 K,0,0,0,0,fNb,0,...,0,0,0,0,0,0,0,0,0,0
4,13,early,VKS,18.8 K,0,0,0,4,Guigo,0,...,1,0,0,0,0,0,0,0,0,0
5,14,early,ITZ,21.3 K,0,0,0,1,Zzk,1,...,0,1,0,0,0,0,0,0,0,0
6,15,early,ITZ,30.4 K,0,0,1,5,Zzk,3,...,0,0,0,0,1,0,0,1,0,0
7,16,early,ITZ,18.0 K,0,0,0,6,Zzk,0,...,0,1,0,0,0,0,0,0,0,0
8,17,early,PNG,17.3 K,0,0,0,3,Wizer,1,...,0,0,0,1,0,0,0,0,0,1
9,18,early,PNG,19.9 K,0,0,0,0,Wizer,0,...,0,0,0,0,0,0,1,0,0,0
10,19,early,LLL,17.2 K,0,0,0,4,Robo,1,...,0,0,0,1,0,0,0,0,0,1
11,2,early,VKS,26.3 K,0,0,1,3,Guigo,0,...,0,0,0,0,1,0,1,0,0,0

In [140]:
# Remove " K" from the end of the string and converts to numeric
data['blue_team_gold'] = data['blue_team_gold'].str.replace('K', '').astype(float)
data['blue_team_top_gold'] = data['blue_team_top_gold'].str.replace('K', '').astype(float)
data['blue_team_jungle_gold'] = data['blue_team_jungle_gold'].str.replace('K', '').astype(float)
data['blue_team_mid_gold'] = data['blue_team_mid_gold'].str.replace('K', '').astype(float)
data['blue_team_bottom_gold'] = data['blue_team_bottom_gold'].str.replace('K', '').astype(float)
data['blue_team_support_gold'] = data['blue_team_support_gold'].str.replace('K', '').astype(float)

data['red_team_gold'] = data['red_team_gold'].str.replace('K', '').astype(float)
data['red_team_top_gold'] = data['red_team_top_gold'].str.replace('K', '').astype(float)
data['red_team_jungle_gold'] = data['red_team_jungle_gold'].str.replace('K', '').astype(float)
data['red_team_mid_gold'] = data['red_team_mid_gold'].str.replace('K', '').astype(float)
data['red_team_bottom_gold'] = data['red_team_bottom_gold'].str.replace('K', '').astype(float)
data['red_team_support_gold'] = data['red_team_support_gold'].str.replace('K', '').astype(float)

data.head(12)

,game,game_time,blue_team,blue_team_gold,blue_team_inhibitors,blue_team_barons,blue_team_towers,blue_team_kills,blue_team_top,blue_team_top_kills,...,blue_cloud_dragon,blue_ocean_dragon,blue_infernal_dragon,blue_chemtech_dragon,red_hextec_dragon,red_mountain_dragon,red_cloud_dragon,red_ocean_dragon,red_infernal_dragon,red_chemtech_dragon
0,1,early,FX,20.5,0,0,0,3,Tay,3,...,0,0,0,0,0,0,0,0,0,0
1,10,early,LLL,18.7,0,0,0,4,Robo,0,...,0,0,0,0,1,0,0,0,0,0
2,11,early,RED,2.5,0,0,0,0,fNb,0,...,0,0,0,0,0,0,0,0,0,0
3,12,early,RED,2.5,0,0,0,0,fNb,0,...,0,0,0,0,0,0,0,0,0,0
4,13,early,VKS,18.8,0,0,0,4,Guigo,0,...,1,0,0,0,0,0,0,0,0,0
5,14,early,ITZ,21.3,0,0,0,1,Zzk,1,...,0,1,0,0,0,0,0,0,0,0
6,15,early,ITZ,30.4,0,0,1,5,Zzk,3,...,0,0,0,0,1,0,0,1,0,0
7,16,early,ITZ,18.0,0,0,0,6,Zzk,0,...,0,1,0,0,0,0,0,0,0,0
8,17,early,PNG,17.3,0,0,0,3,Wizer,1,...,0,0,0,1,0,0,0,0,0,1
9,18,early,PNG,19.9,0,0,0,0,Wizer,0,...,0,0,0,0,0,0,1,0,0,0
10,19,early,LLL,17.2,0,0,0,4,Robo,1,...,0,0,0,1,0,0,0,0,0,1
11,2,early,VKS,26.3,0,0,1,3,Guigo,0,...,0,0,0,0,1,0,1,0,0,0

In [141]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 87 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   game                       96 non-null     int64
 1   game_time                  96 non-null     object
 2   blue_team                  96 non-null     object
 3   blue_team_gold             96 non-null     float64
 4   blue_team_inhibitors       96 non-null     int64
 5   blue_team_barons           96 non-null     int64
 6   blue_team_towers           96 non-null     int64
 7   blue_team_kills            96 non-null     int64
 8   blue_team_top              96 non-null     object
 9   blue_team_top_kills        96 non-null     int64
 10  blue_team_top_deaths       96 non-null     int64
 11  blue_team_top_assists      96 non-null     int64
 12  blue_team_top_cs           96 non-null     int64
 13  blue_team_top_gold         96 non-null     float64
 14  blue_team_jungle           96 non-null     object
 15  blue_team_jungle_kills     96 non-null     int64
 16  blue_team_jungle_deaths    96 non-null     int64
 17  blue_team_jungle_assists   96 non-null     int64
 18  blue_team_jungle_cs        96 non-null     int64
 19  blue_team_jungle_gold      96 non-null     float64
 20  blue_team_mid              96 non-null     object
 21  blue_team_mid_kills        96 non-null     int64
 22  blue_team_mid_deaths       96 non-null     int64
 23  blue_team_mid_assists      96 non-null     int64
 24  blue_team_mid_cs           96 non-null     int64
 25  blue_team_mid_gold         96 non-null     float64
 26  blue_team_bottom           96 non-null     object
 27  blue_team_bottom_kills     96 non-null     int64
 28  blue_team_bottom_deaths    96 non-null     int64
 29  blue_team_bottom_assists   96 non-null     int64
 30  blue_team_bottom_cs        96 non-null     int64
 31  blue_team_bottom_gold      96 non-null     float64
 32  blue_team_support          96 non-null     object
 33  blue_team_support_kills    96 non-null     int64
 34  blue_team_support_deaths   96 non-null     int64
 35  blue_team_support_assists  96 non-null     int64
 36  blue_team_support_cs       96 non-null     int64
 37  blue_team_support_gold     96 non-null     float64
 38  red_team                   96 non-null     object
 39  red_team_gold              96 non-null     float64
 40  red_team_inhibitors        96 non-null     int64
 41  red_team_barons            96 non-null     int64
 42  red_team_towers            96 non-null     int64
 43  red_team_kills             96 non-null     int64
 44  red_team_top               96 non-null     object
 45  red_team_top_kills         96 non-null     int64
 46  red_team_top_deaths        96 non-null     int64
 47  red_team_top_assists       96 non-null     int64
 48  red_team_top_cs            96 non-null     int64
 49  red_team_top_gold          96 non-null     float64
 50  red_team_jungle            96 non-null     object
 51  red_team_jungle_kills      96 non-null     int64
 52  red_team_jungle_deaths     96 non-null     int64
 53  red_team_jungle_assists    96 non-null     int64
 54  red_team_jungle_cs         96 non-null     int64
 55  red_team_jungle_gold       96 non-null     float64
 56  red_team_mid               96 non-null     object
 57  red_team_mid_kills         96 non-null     int64
 58  red_team_mid_deaths        96 non-null     int64
 59  red_team_mid_assists       96 non-null     int64
 60  red_team_mid_cs            96 non-null     int64
 61  red_team_mid_gold          96 non-null     float64
 62  red_team_bottom            96 non-null     object
 63  red_team_bottom_kills      96 non-null     int64
 64  red_team_bottom_deaths     96 non-null     int64
 65  red_team_bottom_assists    96 non-null     int64
 66  red_team_bottom_cs         96 non-null     int64
 67  red_team_bottom_gold       96 non-null     float64
 68  red_team_support           96 non-null     object
 69  red_team_support_kills     96 non-null     int64
 70  red_team_support_deaths    96 non-null     int64
 71  red_team_support_assists   96 non-null     int64
 72  red_team_support_cs        96 non-null     int64
 73  red_team_support_gold      96 non-null     float64
 74  team_winner                96 non-null     object
 75  blue_hextec_dragon         96 non-null     int64
 76  blue_mountain_dragon       96 non-null     int64
 77  blue_cloud_dragon          96 non-null     int64
 78  blue_ocean_dragon          96 non-null     int64
 79  blue_infernal_dragon       96 non-null     int64
 80  blue_chemtech_dragon       96 non-null     int64
 81  red_hextec_dragon          96 non-null     int64
 82  red_mountain_dragon        96 non-null     int64
 83  red_cloud_dragon           96 non-null     int64
 84  red_ocean_dragon           96 non-null     int64
 85  red_infernal_dragon        96 non-null     int64
 86  red_chemtech_dragon        96 non-null     int64
dtypes: float64(12), int64(61), object(14)
memory usage: 65.4+ KB

In [142]:
# Seleciona aleatoriamete 4 partidas
game_range = np.random.randint(1, 32, 4)

# Seleciona as partidas com a coluna game no range selecionado
data_sample = data[data['game'].isin(game_range)]

print('Partidas selecionadas: ', game_range)

Partidas selecionadas:  [ 7 26 19 23]

In [143]:
data_sample

,game,game_time,blue_team,blue_team_gold,blue_team_inhibitors,blue_team_barons,blue_team_towers,blue_team_kills,blue_team_top,blue_team_top_kills,...,blue_cloud_dragon,blue_ocean_dragon,blue_infernal_dragon,blue_chemtech_dragon,red_hextec_dragon,red_mountain_dragon,red_cloud_dragon,red_ocean_dragon,red_infernal_dragon,red_chemtech_dragon
10,19,early,LLL,17.2,0,0,0,4,Robo,1,...,0,0,0,1,0,0,0,0,0,1
15,23,early,ITZ,25.0,0,0,0,3,Zzk,0,...,0,0,0,0,1,1,0,0,0,0
18,26,early,PNG,19.8,0,0,0,0,Wizer,0,...,0,1,0,0,0,0,1,0,0,0
29,7,early,ITZ,2.5,0,0,0,0,Zzk,0,...,0,0,0,0,0,0,0,0,0,0
42,19,late,LLL,58.6,2,1,10,21,Robo,3,...,0,0,0,1,0,0,1,0,0,1
47,23,late,ITZ,70.3,0,0,4,18,Zzk,2,...,0,0,0,2,1,1,0,0,0,2
50,26,late,PNG,47.9,0,0,0,2,Wizer,0,...,0,1,0,0,0,0,1,0,3,0
61,7,late,ITZ,77.7,0,1,5,14,Zzk,6,...,3,0,1,0,1,0,0,0,0,0
74,19,mid,LLL,17.4,0,0,0,4,Robo,1,...,0,0,0,1,0,0,0,0,0,1
79,23,mid,ITZ,45.6,0,0,4,11,Zzk,1,...,0,0,0,2,1,1,0,0,0,2
82,26,mid,PNG,35.4,0,0,0,1,Wizer,0,...,0,1,0,0,0,0,1,0,1,0
93,7,mid,ITZ,29.1,0,0,1,4,Zzk,2,...,0,0,1,0,1,0,0,0,0,0

In [144]:
data_train = data[data['game'].isin(game_range) == False]
data_test = data_sample[data_sample['game_time'] == 'early']

In [145]:
# drop the 'game' column
data_train.drop('game', axis=1, inplace=True)
data_test.drop('game', axis=1, inplace=True)

C:\Users\Marlon\AppData\Local\Temp\ipykernel_18160\1229804565.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_train.drop('game', axis=1, inplace=True)
C:\Users\Marlon\AppData\Local\Temp\ipykernel_18160\1229804565.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_test.drop('game', axis=1, inplace=True)

In [146]:
numeric_features = data_test.select_dtypes(include=[np.number])
numeric_features.columns

Index(['blue_team_gold', 'blue_team_inhibitors', 'blue_team_barons',
       'blue_team_towers', 'blue_team_kills', 'blue_team_top_kills',
       'blue_team_top_deaths', 'blue_team_top_assists', 'blue_team_top_cs',
       'blue_team_top_gold', 'blue_team_jungle_kills',
       'blue_team_jungle_deaths', 'blue_team_jungle_assists',
       'blue_team_jungle_cs', 'blue_team_jungle_gold', 'blue_team_mid_kills',
       'blue_team_mid_deaths', 'blue_team_mid_assists', 'blue_team_mid_cs',
       'blue_team_mid_gold', 'blue_team_bottom_kills',
       'blue_team_bottom_deaths', 'blue_team_bottom_assists',
       'blue_team_bottom_cs', 'blue_team_bottom_gold',
       'blue_team_support_kills', 'blue_team_support_deaths',
       'blue_team_support_assists', 'blue_team_support_cs',
       'blue_team_support_gold', 'red_team_gold', 'red_team_inhibitors',
       'red_team_barons', 'red_team_towers', 'red_team_kills',
       'red_team_top_kills', 'red_team_top_deaths', 'red_team_top_assists',
       'red_team_top_cs', 'red_team_top_gold', 'red_team_jungle_kills',
       'red_team_jungle_deaths', 'red_team_jungle_assists',
       'red_team_jungle_cs', 'red_team_jungle_gold', 'red_team_mid_kills',
       'red_team_mid_deaths', 'red_team_mid_assists', 'red_team_mid_cs',
       'red_team_mid_gold', 'red_team_bottom_kills', 'red_team_bottom_deaths',
       'red_team_bottom_assists', 'red_team_bottom_cs', 'red_team_bottom_gold',
       'red_team_support_kills', 'red_team_support_deaths',
       'red_team_support_assists', 'red_team_support_cs',
       'red_team_support_gold', 'blue_hextec_dragon', 'blue_mountain_dragon',
       'blue_cloud_dragon', 'blue_ocean_dragon', 'blue_infernal_dragon',
       'blue_chemtech_dragon', 'red_hextec_dragon', 'red_mountain_dragon',
       'red_cloud_dragon', 'red_ocean_dragon', 'red_infernal_dragon',
       'red_chemtech_dragon'],
      dtype='object')

In [147]:
#change dtype object to category
for col in data_test.columns:
    if data_test[col].dtype == 'object':
        data_test[col] = data_test[col].astype('category')

for col in data_train.columns:
    if data_train[col].dtype == 'object':
        data_train[col] = data_train[col].astype('category')

C:\Users\Marlon\AppData\Local\Temp\ipykernel_18160\3757224261.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_test[col] = data_test[col].astype('category')
C:\Users\Marlon\AppData\Local\Temp\ipykernel_18160\3757224261.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_test[col] = data_test[col].astype('category')
C:\Users\Marlon\AppData\Local\Temp\ipykernel_18160\3757224261.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_test[col] = data_test[col].astype('category')
C:\Users\Marlon\AppData\Local\Temp\ipykernel_18160\3757224261.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_test[col] = data_test[col].astype('category')
C:\Users\Marlon\AppData\Local\Temp\ipykernel_18160\3757224261.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_test[col] = data_test[col].astype('category')
C:\Users\Marlon\AppData\Local\Temp\ipykernel_18160\3757224261.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_test[col] = data_test[col].astype('category')
C:\Users\Marlon\AppData\Local\Temp\ipykernel_18160\3757224261.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_test[col] = data_test[col].astype('category')
C:\Users\Marlon\AppData\Local\Temp\ipykernel_18160\3757224261.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_test[col] = data_test[col].astype('category')
C:\Users\Marlon\AppData\Local\Temp\ipykernel_18160\3757224261.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_test[col] = data_test[col].astype('category')
C:\Users\Marlon\AppData\Local\Temp\ipykernel_18160\3757224261.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_test[col] = data_test[col].astype('category')
C:\Users\Marlon\AppData\Local\Temp\ipykernel_18160\3757224261.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_test[col] = data_test[col].astype('category')
C:\Users\Marlon\AppData\Local\Temp\ipykernel_18160\3757224261.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_test[col] = data_test[col].astype('category')
C:\Users\Marlon\AppData\Local\Temp\ipykernel_18160\3757224261.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_test[col] = data_test[col].astype('category')
C:\Users\Marlon\AppData\Local\Temp\ipykernel_18160\3757224261.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_test[col] = data_test[col].astype('category')
C:\Users\Marlon\AppData\Local\Temp\ipykernel_18160\3757224261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_train[col] = data_train[col].astype('category')
C:\Users\Marlon\AppData\Local\Temp\ipykernel_18160\3757224261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_train[col] = data_train[col].astype('category')
C:\Users\Marlon\AppData\Local\Temp\ipykernel_18160\3757224261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_train[col] = data_train[col].astype('category')
C:\Users\Marlon\AppData\Local\Temp\ipykernel_18160\3757224261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_train[col] = data_train[col].astype('category')
C:\Users\Marlon\AppData\Local\Temp\ipykernel_18160\3757224261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_train[col] = data_train[col].astype('category')
C:\Users\Marlon\AppData\Local\Temp\ipykernel_18160\3757224261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_train[col] = data_train[col].astype('category')
C:\Users\Marlon\AppData\Local\Temp\ipykernel_18160\3757224261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_train[col] = data_train[col].astype('category')
C:\Users\Marlon\AppData\Local\Temp\ipykernel_18160\3757224261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_train[col] = data_train[col].astype('category')
C:\Users\Marlon\AppData\Local\Temp\ipykernel_18160\3757224261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_train[col] = data_train[col].astype('category')
C:\Users\Marlon\AppData\Local\Temp\ipykernel_18160\3757224261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_train[col] = data_train[col].astype('category')
C:\Users\Marlon\AppData\Local\Temp\ipykernel_18160\3757224261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_train[col] = data_train[col].astype('category')
C:\Users\Marlon\AppData\Local\Temp\ipykernel_18160\3757224261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_train[col] = data_train[col].astype('category')
C:\Users\Marlon\AppData\Local\Temp\ipykernel_18160\3757224261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_train[col] = data_train[col].astype('category')
C:\Users\Marlon\AppData\Local\Temp\ipykernel_18160\3757224261.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_train[col] = data_train[col].astype('category')

In [148]:
category_features = data_train.select_dtypes(include=['category'])
category_features.drop(['team_winner'], axis=1, inplace=True)
category_features.columns

Index(['game_time', 'blue_team', 'blue_team_top', 'blue_team_jungle',
       'blue_team_mid', 'blue_team_bottom', 'blue_team_support', 'red_team',
       'red_team_top', 'red_team_jungle', 'red_team_mid', 'red_team_bottom',
       'red_team_support'],
      dtype='object')

In [149]:
# from sklearn.model_selection import train_test_split

# RANDOM_SEED = 42
# np.random.seed(RANDOM_SEED)

# X = data.drop('team_winner', axis=1)
# y = data['team_winner']

# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=RANDOM_SEED)

X_train = data_train.drop('team_winner', axis=1)
y_train = data_train['team_winner']

X_test = data_test.drop('team_winner', axis=1)
y_test = data_test['team_winner']

print(X_train.shape)
print(X_test.shape)

(84, 85)
(4, 85)

In [150]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [151]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, PolynomialFeatures, OneHotEncoder
from sklearn.compose import ColumnTransformer

numeric_features = X_train.select_dtypes(include=[np.number]).columns
categorical_features = X_train.select_dtypes(include=['category']).columns

numeric_transformer = Pipeline(steps=[
    ('scaler', StandardScaler()),
    ('poly', PolynomialFeatures(degree=2, include_bias=False))
])

categorical_transformer = Pipeline(steps=[
    ('encoder', OneHotEncoder(categories='auto', drop='first', sparse=False, handle_unknown='ignore'))
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ])

X_train_preprocessed = preprocessor.fit_transform(X_train)
X_test_preprocessed = preprocessor.transform(X_test)

c:\Users\Marlon\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [152]:
#Modelagem usando XGBoost
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score

xgb_model = XGBClassifier(n_estimators=1000, max_depth=3, learning_rate=0.1, random_state=RANDOM_SEED)
xgb_model.fit(X_train_preprocessed, y_train)

y_pred_xgb = xgb_model.predict(X_test_preprocessed)

print('Accuracy Score: {}'.format(accuracy_score(y_test, y_pred_xgb)))

Accuracy Score: 0.25

In [ ]:
from sklearn.model_selection import GridSearchCV

#Modelagem usando XGBoost com tuning de hiperpar√¢metros
param_grid_xgb = {
    'n_estimators': [100, 200, 1000],
    'max_depth': [3, 5, 7],
    'learning_rate': [0.01, 0.1, 0.2]
}

xgb_model = XGBClassifier(random_state=RANDOM_SEED)

gs_xgb = GridSearchCV(estimator=xgb_model, param_grid=param_grid_xgb, cv=5, n_jobs=-1, verbose=2)
gs_xgb.fit(X_train_preprocessed, y_train)

gs_xgb.best_params_

Fitting 5 folds for each of 27 candidates, totalling 135 fits

{'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 1000}

In [ ]:
gs_xgb.best_score_

0.5258333333333333

In [153]:
from sklearn.utils import resample

#Bootsrap usando o modelo XGboost para a multiclasses
model_xgb = XGBClassifier(n_estimators=1000, max_depth=3, learning_rate=0.1, random_state=RANDOM_SEED)
model_xgb.fit(X_train_preprocessed, y_train)

# bootstrap predictions
accuracy_xgb = []
n_iterations = 1000

for i in range(n_iterations):
    X_bs, y_bs = resample(X_train_preprocessed, y_train, replace=True)
    # make predictions
    y_hat = model_xgb.predict(X_bs)
    # evaluate model
    score = accuracy_score(y_bs, y_hat)
    accuracy_xgb.append(score)

In [154]:
#Show metrics of bootstrap
print('Mean Accuracy: {:.3f}'.format(np.mean(accuracy_xgb)))
print('Standard Deviation Accuracy: {:.3f}'.format(np.std(accuracy_xgb)))

Mean Accuracy: 0.963
Standard Deviation Accuracy: 0.022